version: "3.8"

services:
  database:
    container_name: "database"
    image: postgres:latest
    environment:
      - POSTGRES_DB_NAME=test
      - POSTGRES_PASSWORD=abc
      - POSTGRES_USER=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
