version: "3.8"

services:
  backend:
    container_name: "backend"
    build:
      context: ../../
      dockerfile: deployment/docker/Backend.Dockerfile
    command: ["python3", "backend_runner.py"]
    environment:
      DB_HOST: database
      DB_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    container_name: "database"
    image: postgres:latest
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: abc
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
