# THIS CODE HAS BEEN AUTOGENERATED WITH sqlacodegen-v2
from sqlalchemy import BigInteger, DateTime, PrimaryKeyConstraint, String, UniqueConstraint, text, Boolean
from sqlalchemy.orm import mapped_column

from src.config.database import Base


class User(Base):
    __tablename__ = 'user'
  
    id = mapped_column(BigInteger)
    first_name = mapped_column(String(48), nullable=False)
    last_name = mapped_column(String(72), nullable=False)
    email = mapped_column(String(255), nullable=False)
    username = mapped_column(String(24), nullable=False)
    password = mapped_column(String(255), nullable=False)
    salt = mapped_column(String(255), nullable=False)
    disabled = mapped_column(Boolean, default=False)
    is_admin = mapped_column(Boolean, default=False)
    otp_validation_token = mapped_column(String(255), nullable=False, unique=True)
    otp_secret = mapped_column(String(255), nullable=True, unique=True)
    created_at = mapped_column(DateTime, nullable=False, server_default=text('CURRENT_TIMESTAMP'))
    updated_at = mapped_column(DateTime, nullable=False, server_default=text('CURRENT_TIMESTAMP'))

    __table_args__ = (
        PrimaryKeyConstraint('id', name='user_pkey'),
        UniqueConstraint('email', name='user_email_key'),
        UniqueConstraint('salt', name='user_salt_key'),
        UniqueConstraint('username', name='user_username_key')
    )
