# THIS CODE HAS BEEN AUTOGENERATED WITH sqlacodegen-v2
from sqlalchemy import BigInteger, Column, DateTime, PrimaryKeyConstraint, String, UniqueConstraint, text
from sqlalchemy.orm import Mapped, declarative_base, mapped_column
from sqlalchemy.orm.base import Mapped

Base = declarative_base()


class User(Base):
    __tablename__ = 'user'
  
    id = mapped_column(BigInteger)
    first_name = mapped_column(String(48), nullable=False)
    last_name = mapped_column(String(72), nullable=False)
    email = mapped_column(String(255), nullable=False)
    username = mapped_column(String(24), nullable=False)
    password = mapped_column(String(255), nullable=False)
    salt = mapped_column(String(255), nullable=False)
    created_at = mapped_column(DateTime, nullable=False, server_default=text('CURRENT_TIMESTAMP'))
    updated_at = mapped_column(DateTime, nullable=False, server_default=text('CURRENT_TIMESTAMP'))

    __table_args__ = (
        PrimaryKeyConstraint('id', name='user_pkey'),
        UniqueConstraint('email', name='user_email_key'),
        UniqueConstraint('salt', name='user_salt_key'),
        UniqueConstraint('username', name='user_username_key')
    )
